---
horcm_install_path: /HORCM
horcm_bin: /HORCM/usr/bin
horcm_instances:
  - instance: 0
    port: 31000
    poll_interval: 1000
    timeout: 3000
  - instance: 1
    port: 31001
    poll_interval: 1000
    timeout: 3000
  - instance: 2
    port: 31002
    poll_interval: 1000
    timeout: 3000
  - instance: 3
    port: 31003
    poll_interval: 1000
    timeout: 3000
ip_command_device:
  type: ip
  local_ip: 192.168.2.92
  array_ip: "192.168.2.91"
local_repo_path: /opt/localrepo
local_repo_url: http://192.168.56.12/localrepo
raidcom_user: "{{ vault_raidcom_user }}"
raidcom_password: "{{ vault_raidcom_password }}"
horcm_conf_base: /etc/horcm
vsp_connection:
  connection_type: "direct"
  username: "{{ vault_raidcom_user }}"
  password: "{{ vault_raidcom_password }}"
