---
horcm_install_path: /HORCM
horcm_bin: /HORCM/usr/bin
horcm_instances:
  - instance: 1001
    port: 34001
    array_ip: "192.168.2.90"
    poll_interval: 1000
    timeout: 3000
  - instance: 1002
    port: 34002
    array_ip: "192.168.2.93"
    poll_interval: 1000
    timeout: 3000
  - instance: 1003
    port: 34003
    array_ip: "192.168.2.92"
    poll_interval: 1000
    timeout: 3000
  - instance: 1004
    port: 34004
    array_ip: "192.168.2.94"
    poll_interval: 1000
    timeout: 3000
ip_command_device:
  type: ip
  local_ip: 192.168.2.91
  array_ip: "192.168.2.90"
local_repo_path: /opt/localrepo
local_repo_url: http://192.168.56.12/localrepo
raidcom_user: "{{ vault_raidcom_user }}"
raidcom_password: "{{ vault_raidcom_password }}"
horcm_conf_base: /etc/horcm
vsp_connection:
  connection_type: "direct"
  username: "{{ vault_raidcom_user }}"
  password: "{{ vault_raidcom_password }}"
