---
# Use localhost since this is the control node itself
ansible_host: 127.0.0.1
ansible_connection: local

# Bridged IP — SAM4H web UI and Cockpit accessible here
bridged_ip: 192.168.2.91
cockpit_url: "https://192.168.2.91:9090"
sam4h_ui_url: "https://192.168.2.91:8080"
