---
- name: Restart horcm
  ansible.builtin.command: "{{ cci_horcm_shutdown_script }} {{ cci_horcm_instance }}"
  listen: Restart horcm
  failed_when: false

- name: Start horcm after restart
  ansible.builtin.command: "{{ cci_horcm_start_script }} {{ cci_horcm_instance }}"
  listen: Restart horcm
