---
cci_horcm_conf_file: "/etc/horcm{{ cci_horcm_instance }}.conf"
cci_horcm_start_script: "{{ cci_horcm_bin }}/horcmstart.sh"
cci_horcm_shutdown_script: "{{ cci_horcm_bin }}/horcmshutdown.sh"
cci_raidcom_bin: "{{ cci_horcm_bin }}/raidcom"
